services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: movieDB
    ports:
      - "5432:5432"

  minio:
    image: minio/minio:latest
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data

  movie-service:
    build: ./movie-service
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - minio
      - video-service
    environment:
      DSN: "host=postgres user=postgres password=postgres dbname=movieDB port=5432 sslmode=disable"
      VIDEO_SERVICE_URL: "http://video-service:8081"

  video-service:
    build: ./video-service
    ports:
      - "8081:8081"
    depends_on:
      - minio
    environment:
      MINIO_ENDPOINT: minio:9000
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
      MINIO_BUCKET: movies

  frontend:
    build: ./movie-frontend
    ports:
      - "5173:5173"
    depends_on:
      - movie-service
      - video-service
    volumes:
      - ./movie-frontend:/app
      - /app/node_modules

volumes:
  minio_data: